server:
  port: 8091
  application:
    name: xfg-dev-tech-app

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7397/eureka/

# 日志
logging:
  level:
    root: debug
  config: classpath:logback-spring.xml